# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_gui.html'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!
import sys
#import pictures_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 478)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.NavigationBar = QtWidgets.QFrame(self.centralwidget)
        self.NavigationBar.setGeometry(QtCore.QRect(-10, 0, 691, 20))
        self.NavigationBar.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(186, 189, 182, 255), stop:0.125 rgba(186, 189, 182, 255), stop:0.25 rgba(162, 164, 158, 255), stop:0.379487 rgba(147, 150, 144, 255), stop:0.5 rgba(141, 143, 138, 255), stop:0.625 rgba(143, 145, 139, 255), stop:0.753846 rgba(143, 145, 139, 255), stop:0.875 rgba(186, 189, 182, 255), stop:0.994845 rgba(186, 189, 182, 255))")
        self.NavigationBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NavigationBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.NavigationBar.setObjectName("NavigationBar")
        self.SettingButton = QtWidgets.QPushButton(self.NavigationBar)
        self.SettingButton.setGeometry(QtCore.QRect(10, 0, 89, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.SettingButton.setFont(font)
        self.SettingButton.setMouseTracking(True)
        self.SettingButton.setTabletTracking(True)
        self.SettingButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.SettingButton.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.SettingButton.setAutoDefault(True)
        self.SettingButton.setObjectName("SettingButton")
        self.ModeButton = QtWidgets.QPushButton(self.NavigationBar)
        self.ModeButton.setGeometry(QtCore.QRect(100, 0, 89, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.ModeButton.setFont(font)
        self.ModeButton.setAutoRepeatDelay(300)
        self.ModeButton.setAutoDefault(True)
        self.ModeButton.setObjectName("ModeButton")
        self.WindowsButton = QtWidgets.QPushButton(self.NavigationBar)
        self.WindowsButton.setGeometry(QtCore.QRect(190, 0, 89, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.WindowsButton.setFont(font)
        self.WindowsButton.setAutoDefault(True)
        self.WindowsButton.setObjectName("WindowsButton")
        self.ButtonFrame = QtWidgets.QFrame(self.centralwidget)
        self.ButtonFrame.setGeometry(QtCore.QRect(420, 20, 261, 160))
        self.ButtonFrame.setStyleSheet("background-image: url(:/9230745422d4ef38d582aed1dbdf47d6.jpeg);")
        self.ButtonFrame.setObjectName("ButtonFrame")
        self.formLayout = QtWidgets.QFormLayout(self.ButtonFrame)
        self.formLayout.setObjectName("formLayout")
        self.StartButton = QtWidgets.QPushButton(self.ButtonFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.StartButton.setFont(font)
        self.StartButton.setIconSize(QtCore.QSize(16, 16))
        self.StartButton.setObjectName("StartButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.StartButton)
        self.StopButton = QtWidgets.QPushButton(self.ButtonFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.StopButton.setFont(font)
        self.StopButton.setObjectName("StopButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.StopButton)
        self.StatusButton = QtWidgets.QPushButton(self.ButtonFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.StatusButton.setFont(font)
        self.StatusButton.setObjectName("StatusButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.StatusButton)
        self.RebootButton = QtWidgets.QPushButton(self.ButtonFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.RebootButton.setFont(font)
        self.RebootButton.setObjectName("RebootButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.RebootButton)
        self.StatusView = QtWidgets.QListView(self.centralwidget)
        self.StatusView.setGeometry(QtCore.QRect(420, 180, 256, 171))
        self.StatusView.setStyleSheet("background-color: rgb(238, 238, 236)")
        self.StatusView.setObjectName("StatusView")
        self.VidioView = QtWidgets.QListView(self.centralwidget)
        self.VidioView.setGeometry(QtCore.QRect(0, 20, 421, 331))
        self.VidioView.setObjectName("VidioView")
        self.StatusScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.StatusScrollBar.setGeometry(QtCore.QRect(660, 180, 21, 171))
        self.StatusScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.StatusScrollBar.setObjectName("StatusScrollBar")
        self.DebugScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.DebugScrollBar.setGeometry(QtCore.QRect(660, 350, 20, 131))
        self.DebugScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.DebugScrollBar.setObjectName("DebugScrollBar")
        self.DebugView = QtWidgets.QListView(self.centralwidget)
        self.DebugView.setGeometry(QtCore.QRect(-5, 351, 691, 131))
        self.DebugView.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.DebugView.setObjectName("DebugView")
        self.DebugView.raise_()
        self.NavigationBar.raise_()
        self.ButtonFrame.raise_()
        self.StatusView.raise_()
        self.VidioView.raise_()
        self.StatusScrollBar.raise_()
        self.DebugScrollBar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.centralwidget.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><br/></p></body></html>"))
        self.SettingButton.setText(_translate("MainWindow", "Setting"))
        self.ModeButton.setText(_translate("MainWindow", "Mode"))
        self.WindowsButton.setText(_translate("MainWindow", "Windows"))
        self.StartButton.setText(_translate("MainWindow", "Start"))
        self.StopButton.setText(_translate("MainWindow", "Stop"))
        self.StatusButton.setText(_translate("MainWindow", "Status"))
        self.RebootButton.setText(_translate("MainWindow", "Reboot"))

